from enum import Enum


class BorderMode(Enum):
    DONUT = 1
    SOLID = 2
    BASIC = 3
    NONE = 4


# Agents
NB_AGENTS = 10
NB_RANDOM_AGENTS = 0
RANDOM_ACC_FACTOR = 1e2
PERCEPTION_RADIUS = 150

# Starting values
STARTING_MASS_VALUE = 1
STARTING_CHARGE_VALUE = 20
STARTING_DIPOLE_MOMENT = 0
STARTING_POLARIZABILITY = 0
STARTING_STIFFNESS = 1
STARTING_FRICTION = 10
STARTING_SIM_RUNNING = False

# Environment
DIMENSION = 2
GRID_SIZE = 50
BOX_SIZE = 600
BORDER_MODE = BorderMode.DONUT
DELTA_TIME = 0.05

# Forces
GRAVITY = True
WAALS = True
SPRING = True
COULOMB = True

# Forces parameters
SPRING_LENGTH = 50
COULOMB_FACTOR = 5 * 1e3
WAALS_FACTOR = 1e-34
GRAVITY_FACTOR = 5e8
SPRING_FACTOR = 1e-3

# Graphs
DRAW_GRAPHS = True
RANGE_COLLISIONS_GRAPH = 20 #Step for border collision graph

# Visual
PARTICULE_RADIUS = 2
DRAW_PERCEPTION_RADIUS = False
