from enum import Enum


class BorderMode(Enum):
    DONUT = 1
    SOLID = 2
    BASIC = 3
    NONE = 4


# Simulation parameters
DIMENSIONS = 2
NB_OCCURRENCES = 5
NB_AGENTS = 15
BOX_SIZE = 600
BORDER_MODE = BorderMode.SOLID
DELTA_TIME = 0.05
PERCEPTION_RADIUS = 500

# Environment
DIMENSION = 2
GRID_SIZE = 50
TIME_STEP = 0.1

# Forces
GRAVITY = True
WAALS = True
SPRING = True
COULOMB = True

# Forces parameters
SPRING_LENGTH = 50
COULOMB_FACTOR = 5 * 1e3
WAALS_FACTOR = 1e-34
GRAVITY_FACTOR = 5e8
SPRING_FACTOR = 1e-3

# Visual
PARTICULE_RADIUS = 2
RANGE_COLLISIONS_GRAPH = 20