from enum import Enum


class BorderMode(Enum):
    DONUT = 1
    SOLID = 2
    BASIC = 3
    NONE = 4


# Simulation parameters
DIMENSIONS = 2
NB_OCCURRENCES = 5
NB_AGENTS = 20
NB_RANDOM_AGENTS = 1
RANDOM_ACC_FACTOR = 1e2
BOX_SIZE = 600
BORDER_MODE = BorderMode.SOLID
DELTA_TIME = 0.05
PERCEPTION_RADIUS = 500

# Starting values
STARTING_MASS_VALUE = 1
STARTING_CHARGE_VALUE = 30
STARTING_DIPOLE_MOMENT = 0
STARTING_POLARIZABILITY = 0
STARTING_STIFFNESS = 10
STARTING_FRICTION = 20
STARTING_SIM_RUNNING = True

# Environment
DIMENSION = 2
GRID_SIZE = 50

# Forces
GRAVITY = True
WAALS = True
SPRING = True
COULOMB = True

# Forces parameters
SPRING_LENGTH = 50
COULOMB_FACTOR = 5 * 1e3
WAALS_FACTOR = 1e-34
GRAVITY_FACTOR = 5e8
SPRING_FACTOR = 1e-3

# Visual
PARTICULE_RADIUS = 2
RANGE_COLLISIONS_GRAPH = 20
DRAW_GRAPHS = True
